import { Injectable, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ProspectSegment } from '../types';
import { firstValueFrom } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class SegmentService {
  private http = inject(HttpClient);
  private apiUrl = 'http://localhost:3001/api/segments';

  async getSegments(): Promise<ProspectSegment[]> {
    const url = `${this.apiUrl}`;
    try {
      const response = await firstValueFrom(this.http.get<{ status: string, data: any[] }>(url));
      return response.data.map(dto => this.mapBackendToFrontend(dto));
    } catch (e) {
      console.error('API Error', e);
      return [];
    }
  }

  async getSegment(id: string): Promise<ProspectSegment | undefined> {
    const url = `${this.apiUrl}/${id}`;
    try {
      const response = await firstValueFrom(this.http.get<{ status: string, data: any }>(url));
      return this.mapBackendToFrontend(response.data);
    } catch (e) {
      console.error('API Error', e);
      return undefined;
    }
  }

  async saveSegment(segmentToSave: Partial<ProspectSegment>): Promise<void> {
    const payload = { ...segmentToSave };

    // Backend expects ruleGroups to be JSON. Frontend types match Backend JSON structure.

    try {
      if (segmentToSave.id && !segmentToSave.id.startsWith('sg_')) { // sg_ is mock ID prefix, but maybe backend uses UUID?
        // If ID exists and assumes real, update.
        // But if we are Creating, we might not have ID.
        // If mock ID, we should POST? No, mock IDs are generated by frontend mock.
        // If we are wired to backend, we likely get UUIDs.
        // So if ID exists, PATCH.
        await firstValueFrom(this.http.patch(`${this.apiUrl}/${segmentToSave.id}`, payload));
      } else {
        // Create
        await firstValueFrom(this.http.post(this.apiUrl, payload));
      }
    } catch (e) {
      console.error('API Save Error', e);
      throw e;
    }
  }

  async deleteSegment(segmentId: string): Promise<void> {
    try {
      await firstValueFrom(this.http.delete(`${this.apiUrl}/${segmentId}`));
    } catch (e) {
      console.error('API Delete Error', e);
      throw e;
    }
  }

  private mapBackendToFrontend(dto: any): ProspectSegment {
    return {
      id: dto.id,
      name: dto.name,
      description: dto.description || '',
      type: dto.type || 'Dynamic',
      rulesCount: dto.ruleGroups ? dto.ruleGroups.reduce((acc: number, g: any) => acc + (g.rules?.length || 0), 0) : 0,
      members: dto.members || 0,
      memberChange: 0, // Not in backend yet
      updated: dto.updatedAt,
      ruleGroups: dto.ruleGroups || []
    };
  }
}