import { Injectable, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Workflow, WorkflowNode, PaletteNode, WorkflowTemplate } from '../types';
import { MOCK_WORKFLOW_NODES_CATALOG, MOCK_WORKFLOW_TEMPLATES } from '../data/mock-data';
import { firstValueFrom } from 'rxjs';

// Helper for deep cloning
function deepClone<T>(obj: T): T {
  return JSON.parse(JSON.stringify(obj));
}

@Injectable({
  providedIn: 'root',
})
export class WorkflowService {
  private http = inject(HttpClient);
  private apiUrl = 'http://localhost:3001/api/workflows';

  private catalog = signal<PaletteNode[]>(MOCK_WORKFLOW_NODES_CATALOG);
  private templates = signal<WorkflowTemplate[]>(MOCK_WORKFLOW_TEMPLATES);

  async getWorkflows(): Promise<Workflow[]> {
    const url = `${this.apiUrl}`;
    try {
      const response = await firstValueFrom(this.http.get<{ status: string, data: any[] }>(url));
      return response.data.map(dto => this.mapBackendToFrontend(dto));
    } catch (e) {
      console.error('API Error', e);
      return [];
    }
  }

  async getWorkflow(id: string): Promise<Workflow | undefined> {
    const url = `${this.apiUrl}/${id}`;
    try {
      const response = await firstValueFrom(this.http.get<{ status: string, data: any }>(url));
      return this.mapBackendToFrontend(response.data);
    } catch (e) {
      console.error('API Error', e);
      return undefined;
    }
  }

  getNodesCatalog(): Promise<PaletteNode[]> {
    // Catalog is static for now, or fetch from backend if we had an endpoint
    return Promise.resolve(deepClone(this.catalog()));
  }

  getTemplates(): Promise<WorkflowTemplate[]> {
    return Promise.resolve(deepClone(this.templates()));
  }

  async saveWorkflow(workflowToSave: Workflow): Promise<Workflow> {
    const payload = this.mapFrontendToBackend(workflowToSave);

    // Check if ID is mock-like or real?
    // If it starts with wf_, it's mock (generated by frontend 'createNewWorkflow')
    // Backend likely returns UUID.

    // IMPORTANT: If we are saving a 'new' workflow that hasn't been persisted, POST.
    // Use a flag or check ID format?
    // Let's rely on: if validation shows it exists? NO.
    // If ID contains "wf_", assumes it's temporary?
    // But verify if backend preserves IDs or generates new ones.
    // Backend `create` usually generates ID.

    const isNew = workflowToSave.id.startsWith('wf_');

    try {
      let savedDto;
      if (isNew) {
        const res = await firstValueFrom(this.http.post<{ status: string, data: any }>(this.apiUrl, payload));
        savedDto = res.data;
      } else {
        const res = await firstValueFrom(this.http.patch<{ status: string, data: any }>(`${this.apiUrl}/${workflowToSave.id}`, payload));
        savedDto = res.data;
      }
      return this.mapBackendToFrontend(savedDto);
    } catch (e) {
      console.error('API Save Error', e);
      throw e;
    }
  }

  async deleteWorkflow(workflowId: string): Promise<void> {
    try {
      await firstValueFrom(this.http.delete(`${this.apiUrl}/${workflowId}`));
    } catch (e) {
      console.error('API Delete Error', e);
      throw e;
    }
  }

  async updateWorkflowStatus(workflowId: string, status: Workflow['status']): Promise<void> {
    // Backend allows PATCH status
    try {
      await firstValueFrom(this.http.patch(`${this.apiUrl}/${workflowId}`, { status }));
    } catch (e) {
      console.error('API Status Update Error', e);
      throw e;
    }
  }

  createNewWorkflow(): Promise<Workflow> {
    // This creates a Client-Side Draft. Not persisted until Save.
    const newWorkflow: Workflow = {
      id: `wf_${Date.now()}`,
      name: 'Untitled Workflow',
      description: 'No description provided.',
      trigger: 'Not configured',
      status: 'draft',
      stats: { enrolled: 0, sent: 0, converted: 0 },
      modified: new Date().toLocaleDateString(),
      nodes: [],
      edges: [],
    };
    return Promise.resolve(newWorkflow);
  }

  createWorkflowFromTemplate(templateId: string): Promise<Workflow> {
    // Mock logic for templates (client side only)
    const template = this.templates().find(t => t.id === templateId);
    if (!template) throw new Error('Template not found');

    const newWorkflow: Workflow = {
      id: `wf_${Date.now()}`,
      ...deepClone(template.workflow),
      status: 'draft',
      stats: { enrolled: 0, sent: 0, converted: 0 },
      modified: new Date().toLocaleDateString(),
    };
    return Promise.resolve(newWorkflow);
  }

  // --- MAPPERS ---

  private getTriggerText(triggerNode: WorkflowNode | undefined): string {
    if (!triggerNode) return 'Not configured';
    let text: string = triggerNode.subType;
    // Map SubType to Text
    if (triggerNode.subType === 'Joined Segment' && triggerNode.settings.segmentId) {
      text = `Joins '${triggerNode.settings.segmentId}' segment`; // We might need Segment Name lookup
    } else if (triggerNode.subType === 'Email Opened') {
      text = 'Opens Email';
    }
    return text;
  }

  private mapBackendToFrontend(dto: any): Workflow {
    // Backend: trigger is JSON. Frontend: trigger is String.
    // DTO has nodes (JSON or object).

    const nodes = typeof dto.nodes === 'string' ? JSON.parse(dto.nodes) : dto.nodes || [];
    const edges = typeof dto.edges === 'string' ? JSON.parse(dto.edges) : dto.edges || [];

    // Derive trigger string from Nodes (preferred) or Backend Trigger JSON
    const triggerNode = nodes.find((n: any) => n.type === 'Trigger');
    const triggerText = this.getTriggerText(triggerNode);

    return {
      id: dto.id,
      name: dto.name,
      description: dto.description || '',
      trigger: triggerText, // Display string
      status: dto.status?.toLowerCase() || 'draft',
      stats: { enrolled: 0, sent: 0, converted: 0 }, // Backend doesn't have stats yet
      modified: dto.updatedAt,
      nodes: nodes,
      edges: edges
    };
  }

  private mapFrontendToBackend(wf: Workflow): any {
    // We must construct the Backend Trigger JSON from the Nodes
    // Backend listener needs { type, segmentId, etc }

    const triggerNode = wf.nodes.find(n => n.type === 'Trigger');
    let backendTrigger: any = { type: 'manual' }; // Default

    if (triggerNode) {
      if (triggerNode.subType === 'Joined Segment') {
        backendTrigger = {
          type: 'segment_entry',
          segmentId: triggerNode.settings?.segmentId
        };
      } else if (triggerNode.subType === 'Email Opened') {
        backendTrigger = {
          type: 'email_opened',
          campaignId: triggerNode.settings?.campaignId
        };
      }
      // Add more mappings as needed
    }

    return {
      name: wf.name,
      description: wf.description,
      status: wf.status?.toUpperCase(),
      trigger: backendTrigger, // JSON object
      nodes: wf.nodes,
      edges: wf.edges
    };
  }
}